# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gray/mines/computer_graphics/MPGraphics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gray/mines/computer_graphics/MPGraphics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gray/mines/computer_graphics/MPGraphics/CMakeFiles /home/gray/mines/computer_graphics/MPGraphics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gray/mines/computer_graphics/MPGraphics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mp

# Build rule for target.
mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mp
.PHONY : mp

# fast build rule for target.
mp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/build
.PHONY : mp/fast

ArcballCamera.o: ArcballCamera.cpp.o
.PHONY : ArcballCamera.o

# target to build an object file
ArcballCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/ArcballCamera.cpp.o
.PHONY : ArcballCamera.cpp.o

ArcballCamera.i: ArcballCamera.cpp.i
.PHONY : ArcballCamera.i

# target to preprocess a source file
ArcballCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/ArcballCamera.cpp.i
.PHONY : ArcballCamera.cpp.i

ArcballCamera.s: ArcballCamera.cpp.s
.PHONY : ArcballCamera.s

# target to generate assembly for a file
ArcballCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/ArcballCamera.cpp.s
.PHONY : ArcballCamera.cpp.s

Lucid.o: Lucid.cpp.o
.PHONY : Lucid.o

# target to build an object file
Lucid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Lucid.cpp.o
.PHONY : Lucid.cpp.o

Lucid.i: Lucid.cpp.i
.PHONY : Lucid.i

# target to preprocess a source file
Lucid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Lucid.cpp.i
.PHONY : Lucid.cpp.i

Lucid.s: Lucid.cpp.s
.PHONY : Lucid.s

# target to generate assembly for a file
Lucid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Lucid.cpp.s
.PHONY : Lucid.cpp.s

MPEngine.o: MPEngine.cpp.o
.PHONY : MPEngine.o

# target to build an object file
MPEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/MPEngine.cpp.o
.PHONY : MPEngine.cpp.o

MPEngine.i: MPEngine.cpp.i
.PHONY : MPEngine.i

# target to preprocess a source file
MPEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/MPEngine.cpp.i
.PHONY : MPEngine.cpp.i

MPEngine.s: MPEngine.cpp.s
.PHONY : MPEngine.s

# target to generate assembly for a file
MPEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/MPEngine.cpp.s
.PHONY : MPEngine.cpp.s

Plane.o: Plane.cpp.o
.PHONY : Plane.o

# target to build an object file
Plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Plane.cpp.o
.PHONY : Plane.cpp.o

Plane.i: Plane.cpp.i
.PHONY : Plane.i

# target to preprocess a source file
Plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Plane.cpp.i
.PHONY : Plane.cpp.i

Plane.s: Plane.cpp.s
.PHONY : Plane.s

# target to generate assembly for a file
Plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Plane.cpp.s
.PHONY : Plane.cpp.s

UFO.o: UFO.cpp.o
.PHONY : UFO.o

# target to build an object file
UFO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/UFO.cpp.o
.PHONY : UFO.cpp.o

UFO.i: UFO.cpp.i
.PHONY : UFO.i

# target to preprocess a source file
UFO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/UFO.cpp.i
.PHONY : UFO.cpp.i

UFO.s: UFO.cpp.s
.PHONY : UFO.s

# target to generate assembly for a file
UFO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/UFO.cpp.s
.PHONY : UFO.cpp.s

Vehicle.o: Vehicle.cpp.o
.PHONY : Vehicle.o

# target to build an object file
Vehicle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Vehicle.cpp.o
.PHONY : Vehicle.cpp.o

Vehicle.i: Vehicle.cpp.i
.PHONY : Vehicle.i

# target to preprocess a source file
Vehicle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Vehicle.cpp.i
.PHONY : Vehicle.cpp.i

Vehicle.s: Vehicle.cpp.s
.PHONY : Vehicle.s

# target to generate assembly for a file
Vehicle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/Vehicle.cpp.s
.PHONY : Vehicle.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mp"
	@echo "... ArcballCamera.o"
	@echo "... ArcballCamera.i"
	@echo "... ArcballCamera.s"
	@echo "... Lucid.o"
	@echo "... Lucid.i"
	@echo "... Lucid.s"
	@echo "... MPEngine.o"
	@echo "... MPEngine.i"
	@echo "... MPEngine.s"
	@echo "... Plane.o"
	@echo "... Plane.i"
	@echo "... Plane.s"
	@echo "... UFO.o"
	@echo "... UFO.i"
	@echo "... UFO.s"
	@echo "... Vehicle.o"
	@echo "... Vehicle.i"
	@echo "... Vehicle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

